# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-05 06:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('math', models.PositiveIntegerField()),
                ('chinese', models.PositiveIntegerField()),
            ],
        ),
    ]
