# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-07-11 06:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_auto_20200711_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='is_delete',
            field=models.BooleanField(default=0),
        ),
    ]
